### ISSUE TITLE
Improve the resolution of relative URLs.

### ISSUE THREAD

**Issue by farkaskid** [farkaskid/WebCrawler#16]
Currently, absolute URLs are being generated by simply joining the relative part for the hostName which is not always true.
https://godoc.org/net/url#URL.ResolveReference can be used to systematically resolve relative URLs.

**Comment by mahesh1996** [comment]
@farkaskid Should I start on this?

**Comment by farkaskid** [comment]
Sorry, just raised a PR for this one. 😅  #18

**Comment by farkaskid** [comment]
#18 merged.
