### ISSUE TITLE
Ability to bound by the domain name.

### ISSUE THREAD

**Issue by farkaskid** [farkaskid/WebCrawler#3]
User should be able to bound the domain within a specific domain. 

Proposal: Provide a boolean flag `-bound`. On receiving the flag the crawler will only continue spreading on a URL if it is in the domain of the given URL.

**Comment by farkaskid** [comment]
Pull Request: https://github.com/farkaskid/WebCrawler/pull/7

**Comment by maheshbhuva** [comment]
What about bounding by hostname. Current implementation matches domain anywhere inside URL.

**Comment by farkaskid** [comment]
Fixed the implementation and merged.
