### ISSUE TITLE
Add reporting mechanism.

### ISSUE THREAD

**Issue by farkaskid** [farkaskid/WebCrawler#4]
The crawl should be able to report whilst(preferable) or after the crawling task is finished.

**Comment by farkaskid** [comment]
As there is no requirement of searching the data we can use the gob encoding to store URL map. 
gob encoding: https://blog.golang.org/gobs-of-data

**Comment by mahesh1996** [comment]
If there is no requirement of searching then what will be the usage of collected URLs? And also data written using `gob` can only be read by `go`. What if the client is using a different programming language or wants to process generated URLs in a different programming language?

**Comment by farkaskid** [comment]
This issue is supposed to solve persistence for the core of the crawler.

Persistence needs will depend upon how the content collected from the crawler is going to be processed. The 'Processor' interface is supposed to be used for that purpose.

Right now, there is no implementation of the 'Processor' interface as we are prototyping the core. Once the core is stabilized we can write 'Processor' implementations for different applications.

For example a 'Processor' implementation for a sitemap generator will have very different persistence requirement. 

We will also need an adapter layers that would convert the content collected by the crawler(in gob) to the common formats.

**Comment by farkaskid** [comment]
Basic storage added using JSON and GOB.
