### ISSUE TITLE
Implement a task queue with fixed number of workers.

### ISSUE THREAD

**Issue by farkaskid** [farkaskid/WebCrawler#5]
Currently, an new goroutine is launched for every collected/filtered URL. The number of goroutines are hence uncontrolled. Implement a task queue with fixed number of workers that can be specified by the user through commandline.

**Comment by mahesh1996** [comment]
https://github.com/Jeffail/tunny

**Comment by farkaskid** [comment]
Looks useful. I'll try it in a separate branch.

Also, I have implemented a solution in the executor package. It's simple and highly decoupled from the crawler logic. 

Take a look https://github.com/farkaskid/WebCrawler/tree/add-task-queue?files=1
